program ApisGN;

uses
  Forms,
  DelphiZXIngQRCode in 'Code\External\DelphiZXIngQRCode.pas',
  XSuperJSON in 'Code\External\XSuperJSON.pas',
  XSuperObject in 'Code\External\XSuperObject.pas',
  AccountEndpoints in 'Code\Api Pix\Utils\EndPoints\AccountEndpoints.pas',
  AuthenticationEndpoints in 'Code\Api Pix\Utils\EndPoints\AuthenticationEndpoints.pas',
  ChargesEndpoints in 'Code\Api Pix\Utils\EndPoints\ChargesEndpoints.pas',
  Connections in 'Code\Api Pix\Utils\EndPoints\Connections.pas',
  KeyPixEndpoints in 'Code\Api Pix\Utils\EndPoints\KeyPixEndpoints.pas',
  LocEndpoints in 'Code\Api Pix\Utils\EndPoints\LocEndpoints.pas',
  PixEndpoints in 'Code\Api Pix\Utils\EndPoints\PixEndpoints.pas',
  WebhookEndpoints in 'Code\Api Pix\Utils\EndPoints\WebhookEndpoints.pas',
  BodyAccountClass in 'Code\Api Pix\Utils\Classes\BodyAccountClass.pas',
  BodyChargesClass in 'Code\Api Pix\Utils\Classes\BodyChargesClass.pas',
  BodyPixClass in 'Code\Api Pix\Utils\Classes\BodyPixClass.pas',
  BodyWebhookClass in 'Code\Api Pix\Utils\Classes\BodyWebhookClass.pas',
  uChargeClasses in 'Code\Api Boletos\Utils\Classes\uChargeClasses.pas',
  uCommonTypes in 'Code\Api Boletos\Utils\Classes\uCommonTypes.pas',
  uConnections in 'Code\Api Boletos\Utils\Classes\uConnections.pas',
  uAuthenticationEndpoints in 'Code\Api Boletos\Utils\Endpoints\uAuthenticationEndpoints.pas',
  uChargesEndpoints in 'Code\Api Boletos\Utils\Endpoints\uChargesEndpoints.pas',
  MainCode in 'Code\MainCode.pas' {MainCode},
  MainEmissions in 'Code\Api Boletos\Utils\MainEmissions.pas' {MainEmissions},
  MainPix in 'Code\Api Pix\Utils\MainPix.pas' {MainPix},
  uBaseCustomerTransactionClasses in 'Code\Api Boletos\Utils\Classes\uBaseCustomerTransactionClasses.pas',
  uCustomerClasses in 'Code\Api Boletos\Utils\Classes\uCustomerClasses.pas',
  uPaymentClasses in 'Code\Api Boletos\Utils\Classes\uPaymentClasses.pas',
  uCarnetClasses in 'Code\Api Boletos\Utils\Classes\uCarnetClasses.pas',
  uCarnetEndpoints in 'Code\Api Boletos\Utils\Endpoints\uCarnetEndpoints.pas',
  uPlansEndpoints in 'Code\Api Boletos\Utils\Endpoints\uPlansEndpoints.pas',
  uPaymentTokenClasses in 'Code\Api Boletos\Utils\Classes\uPaymentTokenClasses.pas',
  PrivateKey in 'Code\External\PrivateKey.pas',
  Rsa in 'Code\External\Rsa.pas',
  uOthersEndpoints in 'Code\Api Boletos\Utils\Endpoints\uOthersEndpoints.pas',
  ViewCreateCharge in 'Code\Api Boletos\Utils\Views\Charges\ViewCreateCharge.pas' {ViewCreateCharge},
  ViewCreateLinkCharge in 'Code\Api Boletos\Utils\Views\Charges\ViewCreateLinkCharge.pas' {ViewCreateLinkCharge},
  ViewCreateChargeHistory in 'Code\Api Boletos\Utils\Views\Charges\ViewCreateChargeHistory.pas' {ViewCreateChargeHistory},
  ViewDetailBillet in 'Code\Api Boletos\Utils\Views\Charges\ViewDetailBillet.pas' {ViewDetailBillet},
  ViewUpdateMetadataCharge in 'Code\Api Boletos\Utils\Views\Charges\ViewUpdateMetadataCharge.pas' {ViewUpdateMetadataCharge},
  ViewPayChargeBillet in 'Code\Api Boletos\Utils\Views\Charges\ViewPayChargeBillet.pas' {ViewPayChargeBillet},
  ViewPayCreditCard in 'Code\Api Boletos\Utils\Views\Charges\ViewPayCreditCard.pas' {ViewPayCreditCard},
  ViewUpdateLinkCharge in 'Code\Api Boletos\Utils\Views\Charges\ViewUpdateLinkCharge.pas' {ViewUpdateLinkCharge},
  ViewResendBillet in 'Code\Api Boletos\Utils\Views\Charges\ViewResendBillet.pas' {ViewResendBillet},
  ViewPixAccountConfig in 'Code\Api Pix\Utils\Views\ViewPixAccountConfig.pas' {ViewAccountConfig},
  ViewPixConfigWebhook in 'Code\Api Pix\Utils\Views\ViewPixConfigWebhook.pas' {ViewConfigWebhook},
  ViewPixCreateCharge in 'Code\Api Pix\Utils\Views\ViewPixCreateCharge.pas' {ViewPixCreateCharge},
  ViewPixCreateImmediateCharge in 'Code\Api Pix\Utils\Views\ViewPixCreateImmediateCharge.pas' {ViewCreateImmediateCharge},
  ViewPixDetail in 'Code\Api Pix\Utils\Views\ViewPixDetail.pas' {ViewDetail},
  ViewPixDetailDevolution in 'Code\Api Pix\Utils\Views\ViewPixDetailDevolution.pas' {ViewPixDetailDevolution},
  ViewPixDevolution in 'Code\Api Pix\Utils\Views\ViewPixDevolution.pas' {ViewPixDevolution},
  ViewPixList in 'Code\Api Pix\Utils\Views\ViewPixList.pas' {ViewList},
  ViewPixSend in 'Code\Api Pix\Utils\Views\ViewPixSend.pas' {ViewPixSend},
  ViewPixUpdateCharge in 'Code\Api Pix\Utils\Views\ViewPixUpdateCharge.pas' {ViewUpdateCharge},
  ViewCancelParcel in 'Code\Api Boletos\Utils\Views\Carnet\ViewCancelParcel.pas' {ViewCancelParcel},
  ViewCreateCarnet in 'Code\Api Boletos\Utils\Views\Carnet\ViewCreateCarnet.pas' {ViewCreateCarnet},
  ViewDetailCarnet in 'Code\Api Boletos\Utils\Views\Carnet\ViewDetailCarnet.pas' {ViewDetailCarnet},
  ViewUpdateParcel in 'Code\Api Boletos\Utils\Views\Carnet\ViewUpdateParcel.pas' {ViewUpdateParcel},
  ViewUpdateMetadataCarnet in 'Code\Api Boletos\Utils\Views\Carnet\ViewUpdateMetadataCarnet.pas' {ViewUpdateMetadataCarnet},
  ViewResendParcel in 'Code\Api Boletos\Utils\Views\Carnet\ViewResendParcel.pas' {ViewResendParcel},
  ViewResendCarnet in 'Code\Api Boletos\Utils\Views\Carnet\ViewResendCarnet.pas' {ViewResendCarnet},
  ViewCreateCarnetHistory in 'Code\Api Boletos\Utils\Views\Carnet\ViewCreateCarnetHistory.pas' {ViewCreateCarnetHistory},
  ViewSettleCarnetParcel in 'Code\Api Boletos\Utils\Views\Carnet\ViewSettleCarnetParcel.pas' {ViewSettleCarnetParcel},
  ViewCreatePlan in 'Code\Api Boletos\Utils\Views\Plans\ViewCreatePlan.pas' {ViewCreatePlan},
  ViewGetPlan in 'Code\Api Boletos\Utils\Views\Plans\ViewGetPlan.pas' {ViewGetPlan},
  ViewUpdatePlan in 'Code\Api Boletos\Utils\Views\Plans\ViewUpdatePlan.pas' {ViewUpdatePlan},
  ViewCreateSubscription in 'Code\Api Boletos\Utils\Views\Plans\ViewCreateSubscription.pas' {ViewCreateSubscription},
  ViewCreatePlanHistory in 'Code\Api Boletos\Utils\Views\Plans\ViewCreatePlanHistory.pas' {ViewCreatePlanHistory},
  ViewDetailPlan in 'Code\Api Boletos\Utils\Views\Plans\ViewDetailPlan.pas' {ViewDetailPlan},
  ViewUpdateMetadataPlan in 'Code\Api Boletos\Utils\Views\Plans\ViewUpdateMetadataPlan.pas' {ViewUpdateMetadataPlan},
  ViewDetailOthers in 'Code\Api Boletos\Utils\Views\Others\ViewDetailOthers.pas' {ViewDetailOthers},
  ViewPayPlan in 'Code\Api Boletos\Utils\Views\Plans\ViewPayPlan.pas' {ViewPayPlan},
  ViewPayPlanCreditCard in 'Code\Api Boletos\Utils\Views\Plans\ViewPayPlanCreditCard.pas' {ViewPayPlanCreditCard},
  ViewPixIdDetail in 'Code\Api Pix\Utils\Views\ViewPixIdDetail.pas' {ViewPixIdDetail},
  ViewPixKeyDetail in 'Code\Api Pix\Utils\Views\ViewPixKeyDetail.pas' {ViewPixKeyDetail},
  ViewPixE2eidDetail in 'Code\Api Pix\Utils\Views\ViewPixE2eidDetail.pas' {ViewPixE2eidDetail},
  ViewPayChargeBilletOneStep in 'Code\Api Boletos\Utils\Views\Charges\ViewPayChargeBilletOneStep.pas' {ViewPayChargeBilletOneStep},
  ViewPayCreditCardOneStep in 'Code\Api Boletos\Utils\Views\Charges\ViewPayCreditCardOneStep.pas' {ViewPayCreditCardOneStep};

{$R *.res}

begin
  Application.Initialize;
  {$IFDEF UNICODE}
  Application.MainFormOnTaskbar := True;
  {$ENDIF}
  Application.CreateForm(MainCode.TMainCode, frmCode);
  Application.Run;
end.
